# Generated by Django 5.1.4 on 2025-01-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cars_count', models.IntegerField()),
                ('cars_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateField()),
            ],
        ),
    ]
