# Generated by Django 5.1.4 on 2025-01-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_carinventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carinventory',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='car',
            name='bio',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='carinventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
