# Generated by Django 5.1.4 on 2025-01-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_carinventory_options_car_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='bio',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
